ShopLapAsus/Controllers/SearchController.cs
using MyConnection;
using PetaPoco;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace ShopLapAsus.Controllers
{
    public class SearchController : Controller
    {
        public ActionResult Search(string keyword, int? page)
        {
            
            if (page == null)
                page = 1;
            MyConnectionDB db = new MyConnectionDB();
            Page<Product> dsspSearch = db.Page<Product>(page.Value, 4, "select * from Product where sp_Ten LIKE '%" +  keyword + " %'");
            return View(dsspSearch);

        }

        public ActionResult Details(int id)
        {
            MyConnectionDB db = new MyConnectionDB();
            return View(db.Single<Product>("WHERE sp_ID = " + id + "", 123));
        }
        // GET: Search
        public ActionResult Index()
        {
            return View();
        }

        // GET: Search/Details/5
       

        // GET: Search/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Search/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Search/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Search/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Search/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Search/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ShopLapAsus/Views/Search/Details.cshtml
@model MyConnection.Product
@using BUS.BUS

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="container-fluid">
    <div class="row">
        <div class="col-md-4">
            <h2>Details</h2>
            <hr />
            <dl class="dl-horizontal">

                <dt>
                    @Html.DisplayNameFor(model => model.sp_Ten)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.sp_Ten)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.sp_HinhAnh)
                </dt>

                <dd>
                    <img src="@Html.DisplayFor(model=>model.sp_HinhAnh)" height="100" width="100" />
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.sp_GiaBan)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.sp_GiaBan)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.sp_GiamGia)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.sp_GiamGia)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.sp_NgayNhap)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.sp_NgayNhap)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.sp_SoLuongTon)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.sp_SoLuongTon)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.sp_SoLuongBan)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.sp_SoLuongBan)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.sp_ManHinh)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.sp_ManHinh)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.sp_HDD)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.sp_HDD)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.sp_ODia)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.sp_ODia)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.sp_BoXuLy)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.sp_BoXuLy)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.sp_DoMong)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.sp_DoMong)
                </dd>


                <dt>
                    @Html.DisplayNameFor(model => model.sp_MoTa)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.sp_MoTa)
                </dd>

            </dl>


            <p>
                <a href="/Cart/AddItem?productID=@Html.DisplayFor(model=>model.sp_ID)&Quantity=1" class="btn btn-danger">Add cart</a>
            </p>
            <p>
                @*@Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |*@
                @Html.ActionLink("Back to List", "Search")
            </p>
        </div>

        <div class="col-md-4">
            <h3>Phần bình luận</h3>
            <form>
                name:<br>
                <input type="text" value="Mickey">
                <br>

                @Html.TextArea("Message", new { rows = 10, cols = 200 })
                <br>
                <input type="submit" value="Bình luận">
                <br>
            </form>
        </div>

        <div class="col-md-4">
            <h3>Sản phẩm liên quan</h3>
            @foreach (var item in ProductBUS.dssp_ZenBook())
            {

                <div class="col-md-3">
                    <div class="thumbnail">
                        <img src="@Html.DisplayFor(m=>item.sp_HinhAnh)" alt="...">
                        <div class="caption">
                            <h4>@Html.DisplayFor(m => item.sp_Ten)</h4>
                            <h4><b>@Html.DisplayFor(m => item.sp_GiamGia) VNĐ</b></h4>
                            <p>...</p>
                            <p> <a href="/Cart/AddItem?productID=@item.sp_ID&Quantity=1" class="btn btn-danger">Add cart</a> <button class="btn btn-info">@Html.ActionLink("Xem", "Details", new { id = item.sp_ID })</button> </p>
                        </div>
                    </div>

                </div>
            }
        </div>


    </div>
</div>

ShopLapAsus/Views/Search/Search.cshtml
@model PetaPoco.Page<MyConnection.Product>
@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Search</h2>
<div class="container body-content">
    <div class="category-hotproduct row">
        @foreach (var item in Model.Items)
        {
            <div class="col-md-3">
                <div class="thumbnail">
                    <img src="@Html.DisplayFor(m=>item.sp_HinhAnh)" alt="...">
                    <div class="caption">
                        <h4>@Html.DisplayFor(m => item.sp_Ten)</h4>
                        <p>..</p>
                        <p><a href="/Cart/AddItem?productID=@Html.DisplayFor(model=>item.sp_ID)&Quantity=1" class="btn btn-danger" role="button">Add Cart</a> <button class="btn btn-info">@Html.ActionLink("Xem", "/Details/", new { id = item.sp_ID })</button></p>
                    </div>
                </div>
            </div>
        }
    </div>
</div>
@*@for(int i = 1; i <= Model.TotalPages; i ++)
    {
        <a href="http://localhost:53159/Products/Index/?page=@i">@i</a>
    }*@

<nav>
    <ul class="pagination">
        @*<li class=""><a href="#" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>*@
        @for (int i = 1; i <= Model.TotalPages; i++)
        {
            <li class="">
                <a href="/Products/Index/?page=@i"> @i <span class="sr-only">(current)</span></a>
            </li>
        }

        @*<li class=""><a href="#" aria-label="Next"><span aria-hidden="true">&raquo;</span></a></li>*@
    </ul>
</nav>