ShopLapAsus/Controllers/CartController.cs
using BUS.BUS;
using MyConnection;
using ShopLapAsus.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace ShopLapAsus.Controllers
{
    
    public class CartController : Controller
    {
        private const string CartSession = "CartSession";
        // GET: Cart
        public ActionResult Index()
        {
            var cart = Session[CartSession];
            var list = new List<CartItem>();
            if(cart != null)
            {
                list = (List<CartItem>)cart;
            }
            return View(list);
        }

        public ActionResult AddItem(int productID, int Quantity)
        {
            var product = new Models.ProductBUS().ViewDetail(productID);
            var cart = Session[CartSession];
            if(cart != null)
            {
                var list = (List<CartItem>)cart;
                if(list.Exists(x=>x.Product.sp_ID == productID))
                {
                    foreach(var item in list)
                    {
                        if(item.Product.sp_ID == productID)
                        {
                            item.Quantity += Quantity;
                        }
                    }
                }
                else
                {
                    var item = new CartItem();
                    item.Product = product;
                    item.Quantity = Quantity;
                    list.Add(item);
                }
                Session[CartSession] = list;
            }
            else
            {
                var item = new CartItem();
                item.Product = product;
                item.Quantity = Quantity;
                var list = new List<CartItem>();
                list.Add(item);
                Session[CartSession] = list;
            }
            return RedirectToAction("Index");
            
        }

        public JsonResult DeleteAll()
        {
            Session[CartSession] = null;
            return Json(new
            {
                status = true
            });
        }

        public JsonResult Delete(long id)
        {
            var sessionCart = (List<CartItem>)Session[CartSession];
            sessionCart.RemoveAll(x => x.Product.sp_ID == id);
            Session[CartSession] = sessionCart;
            return Json(new
            {
                status = true
            });
        }

        public JsonResult Update(string cartModel)
        {
            var jsonCart = new JavaScriptSerializer().Deserialize<List<CartItem>>(cartModel);
            var sessionCart = (List<CartItem>)Session[CartSession];

            foreach (var item in sessionCart)
            {
                var jsonItem = jsonCart.SingleOrDefault(x => x.Product.sp_ID == item.Product.sp_ID);
                if (jsonItem != null)
                {
                    item.Quantity = jsonItem.Quantity;
                }
            }
            Session[CartSession] = sessionCart;
            return Json(new
            {
                status = true
            });
        }
        [Authorize]
        [HttpGet]
        public ActionResult Payment()
        {
            var cart = Session[CartSession];
            var list = new List<CartItem>();
            if (cart != null)
            {
                list = (List<CartItem>)cart;
            }
            return View(list);
        }

        [HttpPost]
        public ActionResult Payment(string shipName,string mobile,string address,string email)
        {
            Models.Order order = new Models.Order();
            
            order.CreatedDate = DateTime.Now;
            order.ShipAddress = address;
            order.ShipMobile = mobile;
            order.ShipName = shipName;
            order.ShipEmail = email;
            
            var Result = MyConnectionDB.GetInstance().Insert(order);
            var cart = (List<CartItem>)Session[CartSession];
            if(cart != null)
            { 
            foreach(var item in cart)
            {
                Models.OrderDetail orderdetail = new Models.OrderDetail();
                orderdetail.ProductID = item.Product.sp_ID;
                orderdetail.Price = item.Product.sp_GiaBan;
                orderdetail.Quality = item.Quantity;
                orderdetail.Total = (item.Product.sp_GiaBan * item.Quantity);
                var Result1 = MyConnectionDB.GetInstance().Insert(orderdetail);
            }
            }
            Session[CartSession] = null;

            return Redirect("/Cart/Succes");
            
        }

        public ActionResult Succes()
        {
            return View();
        }

    }
}

ShopLapAsus/Views/Cart/Index.cshtml
@model List<ShopLapAsus.Models.CartItem>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using Microsoft.AspNet.Identity

@*@if(Request.IsAuthenticated)
{*@ 
    @if(Model != null)
    { 
@section jsFooter{
<script src="/Assets/Admin/client/js/controller/cartController.js"></script>
    }
<h2>Index</h2>
<table class="table">
    <thead>
        <tr>
            <td>Mã sản phẩm</td>
            <td>Tên sản phẩm</td>
            <td>Ảnh sản phẩm</td>
            <td>Số lượng</td>
            <td>Đơn giá</td>
            <td>Thành tiền</td>
            <td></td>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Product.sp_ID</td>
                <td>@item.Product.sp_Ten</td>
                <td><img src="@item.Product.sp_HinhAnh" width="100" /></td>
                <td><input type="text" class="txtQuantity" data-id="@item.Product.sp_ID" value="@item.Quantity" /></td>
                <td>@(item.Product.sp_GiaBan)</td>
                <td>@((item.Product.sp_GiaBan * item.Quantity).ToString("N0"))</td>
                @*<td><a href="#" data-id="@item.Product.ID" class="btn-delete">Xoá</a></td>*@
                <td><a href="#" data-id="@item.Product.sp_ID" class="btn-delete">Xoá</a></td>
            </tr>
        }

    </tbody>
</table>
        <button id="btnContinue" class="btn btn-primary">Tiếp tục mua hàng</button>
        <button id="btnUpdate" class="btn btn-default">Cập nhập giỏ hàng</button>
        <button id="btnDeleteAll" class="btn btn-danger">Xóa giỏ hàng</button>
        <button id="btnPayment" class="btn btn-success">Thanh toán</button>

    }
    else
    {
        <span class="alert alert-danger">Chưa có sản phẩm nào ở giở hàng</span>
    }
@*}*@

ShopLapAsus/Views/Cart/Payment.cshtml
@model List<ShopLapAsus.Models.CartItem>
@{
    ViewBag.Title = "Payment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Payment</h2>

@if (Model != null)
{ 
    <table class="table">
        <thead>
            <tr>
                <td>Mã sản phẩm</td>
                <td>Tên sản phẩm</td>
                <td>Ảnh sản phẩm</td>
                <td>Số lượng</td>
                <td>Đơn giá</td>
                <td>Thành tiền</td>
                <td></td>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Product.sp_ID</td>
                    <td>@item.Product.sp_Ten</td>
                    <td><img src="@item.Product.sp_HinhAnh" width="100" /></td>
                    <td><input type="text" class="txtQuantity" data-id="@item.Product.sp_ID" value="@item.Quantity" /></td>
                    <td>@(item.Product.sp_GiaBan)</td>
                    <td>@((item.Product.sp_GiaBan * item.Quantity).ToString("N0"))</td>
                    @*<td><a href="#" data-id="@item.Product.ID" class="btn-delete">Xoá</a></td>*@
                    @*<td><a href="#" data-id="@item.Product.sp_ID" class="btn-delete">Xoá</a></td>*@
                </tr>
            }

        </tbody>
    </table>
}
<div class="section group">
<div class="col-md-6">
    @using (Html.BeginForm("Payment", "Cart", FormMethod.Post))
            {
        <div class="form-group">
            <label>Người nhận</label>
            <input name="shipName" class="form-control" />
        </div>
            <div class="form-group">
                <label>Điện thoại</label>
                <input name="mobile" class="form-control" />
            </div>
                <div class="form-group">
                    <label>Địa chỉ</label>
                    <input name="address" class="form-control" />
                </div>
                <div class="form-group">
                    <label>Email</label>
                    <input name="email" class="form-control" />
                </div>
                <button type="submit" class="btn">Gửi đơn hàng</button>
    }
</div>

</div>

ShopLapAsus/Views/Cart/Succes.cshtml
@{
    ViewBag.Title = "Succes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Succes</h2>
<div class="alert alert-success">
    Bạn vừa mua hàng thành công.
</div>